sudo: false
language: node_js
node_js:
  - node

install:
  - npm i

script:
    - npm run lint
    - npm run build
    - npm run coverage

after_script:
    - nyc report --reporter=text-lcov | coveralls
